name: Build
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push server
        uses: docker/build-push-action@v6
        with:
          push: true
          labels: org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          tags: ghcr.io/f-wuts/distcc_docker:${{ github.run_number }}
          context: "./distcc_image"
